services:
  youtube-bot:
    build: ./docker
    container_name: youtube-bot-1
    env_file: .env
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./credentials:/app/credentials
      - ./assets:/app/assets
      - ./models:/app/models
    working_dir: /app
    command: ["python3", "bot_main.py"]
    depends_on:
      - vllm
      - auto1111
    restart: unless-stopped

  vllm:
    image: vllm/vllm-openai:latest
    command: ["--model", "gpt-oss/gpt-oss-20b", "--tensor-parallel-size", "1", "--gpu-memory-utilization", "0.9"]
    ports:
      - "8000:8000"
    environment:
      - VLLM_API_KEY=dummy
    restart: unless-stopped
    # Uncomment for GPU access
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]

  auto1111:
    image: ghcr.io/ashleykleynhans/automatic1111-webui:latest
    environment:
      - CLI_ARGS=--listen --xformers --disable-safe-unpickle
    ports:
      - "7860:7860"
    volumes:
      - ./data/sd:/data
    restart: unless-stopped

networks:
  default:
    name: youtube-bot-net
