services:
  youtube-bot:
    build: ./docker
    container_name: youtube-bot-1
    env_file: .env
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./credentials:/app/credentials
      - ./assets:/app/assets
      - ./models:/app/models
    working_dir: /app
    command: ["python3", "bot_main.py"]
    depends_on:
      - vllm
      - auto1111
    restart: "no"

  vllm:
    image: vllm/vllm-openai:latest
    command: ["--model", "openai/gpt-oss-20b", "--tensor-parallel-size", "1", "--gpu-memory-utilization", "0.9"]
    ports:
      - "8000:8000"
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    restart: "no"

  auto1111:
    image: sdwebui/stable-diffusion-webui:latest
    container_name: auto1111
    environment:
      - CLI_ARGS=--listen --api --xformers
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "7860:7860"
    volumes:
      - ./data/sd:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: "no"

networks:
  default:
    name: youtube-bot-net
